---
- name: Provision OpenShift 4 Environment
  hosts: localhost
  connection: local
  vars_files:
    - vault.yml

  roles:
    - role: openshift-installer
      tags:
        - openshift-installer
    - role: ipa
      tags:
        - ipa
    - role: rhv
      tags:
        - rhv
    
- name: Setup Webserver Host
  hosts: webserver
  become: yes
  gather_facts: true
  vars_files:
    - vault.yml

  roles: 
    - role: httpd
      tags:
        - httpd
    # - role: storage
    #   tags:
    #     - storage

- name: Setup Loadbalancer Host
  hosts: loadbalancer
  become: yes
  gather_facts: true

  roles:
    - role: pxe
      tags:
        - pxe
    - role: dhcpd
      tags:
        - dhcpd
    - role: haproxy
      tags:
        - haproxy

# - name: Setup external storage 
#   hosts: storage
#   become: yes
#   gather_facts: true

#   roles: 
#     - geerlingguy.nfs 

- name: Boot CoreOS Nodes
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
   - role: boot-instances
     tags:
        - boot-instances 
