- name: Install DHCP Server Package
  yum:
    name:
      - dhcp
    state: latest

- name: Copy dhcpd.conf Template
  template:
    src: templates/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    setype: dhcp_etc_t

- name: Enable/Start dhcpd Service
  systemd:
    name: dhcpd
    state: restarted
    enabled: yes

- name: Enable dhcp port in firewall
  firewalld:
    service: "{{item}}"
    state: enabled
    zone: "{{firewall_zone}}"
    permanent: yes
    immediate: yes
  with_items:
    - dhcp
    - proxy-dhcp
  
